kind: Service
apiVersion: v1
metadata:
  name: go-app-service
  namespace: gcpug
spec:
  type: LoadBalancer
  selector:
    app: go-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  